### ISSUE TITLE
how to integrate Wikitude to your widget

### ISSUE THREAD

**Issue by alexyellowcube** [joaquinlom/AlloyWikitude#1]
Hi Joaquinlom,

can you please provide some example how to integrate Wikitude with your widget?

**Comment by joaquinlom** [comment]
Hi Alexyellowcube
You need to download the wikitude module from https://www.wikitude.com/download/
after you include in your tiapp.xml.


you need to create the widget and pass an arguments

`var arquitectWorld = args.url; // The url to load on the Wikitude world
var textShare = (args.textShare)?args.textShare: 'Share with '+Ti.App.getName(); //String when you share the screenshot
var actionBarVisible = (args.actionBar !== null)?args.actionBar:true; //If you want an toolbar on the top
var canShare = (args.canShare !== null)?args.canShare:true;
var actionBarColor = (args.actionBarColor)?args.actionBarColor:'#000';
var actionBarTitulo = (args.titulo)?args.titulo:'';
var cameraSoundEnabled = (args.cameraSound)?args.cameraSound:true;
var wikitudeKey = args.wikitudeKey; //THIS IS YOUR WIKITUDE KEY
var wikitudeLibrary = require('com.wikitude.ti');
var augmentedRealityFeatures = (args.ARFeatures)?args.ARFeatures:["2d_tracking"]; //you can put an array with 'Ir' /'geo' / '2d_tracking'
var initialJs = args.initialJs;` //This is a js code that is evaluate on World is loaded event.


you are free to edit your copy :)

**Comment by alexyellowcube** [comment]
Hi Joaquiniom,

Thanks you for your reply and it worked for me. but currently i am facing the issue on open the window from the widget. Here is my code. is it possible to describe more about how to open the window from your widget?

$.index.addEventListener('open', run_widget);

var args = {
	url : "01_ImageTracking_1_ImageOnTarget/index.html", // The url to load on the Wikitude world
	textShare : "", //String when you share the screenshot
	actionBar : true, //If you want an toolbar on the top
	canShare : true,
	actionBarColor : "#000",
	titulo : "",
	cameraSound : true,
	wikitudeKey : 'Mywikitubekey',
	augmentedRealityFeatures : 'image_tracking',
	initialJs : 'test'
	
	
};

function run_widget() {
	var ARVisorWidget = Alloy.createWidget("ARVisor","widget",args);
	ARVisorWidget.open();

}

**Comment by alexyellowcube** [comment]
Hi Joaquiniom,

Thanks you for your quick responsed. i had succeeded load your widget to my app.
But i still have a issues about the initialJs. I not very clear about what should i place into this variable. because i keep having this error ""Can't find variable: initiaJs";" Can you explain more detail about it. thanks you.


/**---------------------------**/
Here is my testing code:

$.index.addEventListener('open', run_widget);

$.index.open();

function run_widget() {
	var args = {
		url : "03_MultipleTargets_1_MultipleTargets/index.html", // The url to load on the Wikitude world
		textShare : "", //String when you share the screenshot
		actionBar : true, //If you want an toolbar on the top
		canShare : true,
		actionBarColor : "#000",
		titulo : "",
		cameraSound : true,
		wikitudeKey : 'mykey',
		augmentedRealityFeatures : 'image_tracking',
		initialJs : 'test'
	
		
		
	};
	
	
       var myWidget = Alloy.createWidget("ARVisor","widget",args);
       myWidget.widget.open();
}

**Comment by joaquinlom** [comment]
Hi, the initialJs is a Javascript code that runs when the World is loaded.
You can put an alert to see. on inside this is what happen when world is
loaded ARView.callJavascript(initialJs); so you can put an
'alert("Loaded");'

**Comment by alexyellowcube** [comment]
thanks you for your help and it work well.

**Comment by joaquinlom** [comment]
Your welcome:)

**Comment by alexyellowcube** [comment]
Hi Joaquinlom,

i having the invalid signature issue on strip_wikitude_framework.sh and wikitude_bitcode.sh as show in the attached when i try publish the app to apple Appstore.  Do you have any idea about these?
![screenshot 2017-11-23 11 36 39](https://user-images.githubusercontent.com/18346408/33158172-9a0283fc-d042-11e7-8c96-7e2b1c5c18c5.png)

**Comment by joaquinlom** [comment]
check out this.
https://support.wikitude.com/support/discussions/topics/5000083810
maybe its help another workaround, try to clean and rebuild.
